import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';

import ReduxProvider from '@/ducks/provider';
import StyledComponentsRegistry from '@/lib/StyledComponent.registry';
import { Web3Modal } from '@/lib/Web3Modal';
import GlobalToast from '@/components/blocks/toasts/Toast';
import TransactionModal from '@/components/blocks/modal/TransactionModal';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ReduxProvider>
                    <Web3Modal>
                        <StyledComponentsRegistry>
                            {children}
                            <GlobalToast />
                            <TransactionModal />
                        </StyledComponentsRegistry>
                    </Web3Modal>
                </ReduxProvider>
            </body>
        </html>
    );
}
